FROM gcr.io/spark-operator/spark-operator:v1beta2-1.2.3-3.1.1

# Add s3a connector
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.3/hadoop-aws-2.7.3.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4.2/aws-java-sdk-1.7.4.2.jar $SPARK_HOME/jars
