name: Build and Push Docker
on:
  push:
    branches:
      - master

jobs:
  build_aws:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Build and Push Spark 3.0.0
      run: |
        export SPARK_VERSION=3.0.0
        export DOCKER_REPO=duyetdev
        wget -q -O spark.tgz http://mirrors.viethosting.com/apache/spark/spark-3.0.0-preview2/spark-3.0.0-preview2-bin-without-hadoop.tgz
        tar zxf spark.tgz
        cd spark-3.0.0-preview2-bin-without-hadoop
        ./bin/docker-image-tool.sh -r $DOCKER_REPO -t v$SPARK_VERSION -p ./kubernetes/dockerfiles/spark/bindings/python/Dockerfile build
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
        ./bin/docker-image-tool.sh -r $DOCKER_REPO -t v$SPARK_VERSION push