name: Build and Push spark-py
on:
  push:
    branches:
      - master

jobs:
  build_spark_py:
    name: Build spark-py
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [v3.1.1-hadoop3]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMAGE_TAG: ${{matrix.tag}}
          BASE: spark-py
        with:
          context: ${{ github.workspace }}
          file: ./${{ env.BASE }}/${{ env.IMAGE_TAG }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.BASE }}:${{ env.IMAGE_TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build_spark_operator:
    name: Build spark-operator
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [v1beta2-1.2.2-3.1.1]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMAGE_TAG: ${{matrix.tag}}
          BASE: spark-operator
        with:
          context: ${{ github.workspace }}
          file: ./${{ env.BASE }}/${{ env.IMAGE_TAG }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.BASE }}:${{ env.IMAGE_TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
